### ISSUE TITLE
Ngrok: Failed to complete tunnel connection

### ISSUE THREAD

**Issue by jepunband** [iinc0gnit0/BlackPhish#13]
**Failed to complete tunnel connection**
-----------------------------------------------------

The connection to http://6e872fae795f.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:8080.

Make sure that a web service is running on localhost:8080 and that it is a valid address.

The error encountered was: dial tcp [::1]:8080: connect: connection refused

**Comment by iinc0gnit0** [comment]
try to run it on port 80

**Comment by hariyebk** [comment]
the local address 127.0.1.1 is not working pls help
