### ISSUE TITLE
Color needs to be changed back after running program without dependencies

### ISSUE THREAD

**Issue by pythonier5001** [iinc0gnit0/BlackPhish#2]
In the first part of blackphish.py it includes the following try-except loop in the beginning of the file:
```python3
try:
    from os import system, getcwd, geteuid
    from time import sleep
    from socket import create_connection, gethostname, gethostbyname
    from distutils.dir_util import copy_tree
except ImportError:
    print("\033[31;1m" + "[!] Import Error, Aborting! \033[0m")
    print("\033[31;1m" + "[!] Please run: \"chmod +x install.sh && ./install.sh\"") # Command to run install.sh # 
    exit(1)
```
The second line in the except block should be `print("\033[31;1m" + "[!] Please run: \"chmod +x install.sh && ./install.sh\"\033[0m")` so that the color will reset.  Otherwise the terminal stays red.

**Comment by iinc0gnit0** [comment]
I will fix that problem in BlackPhish 2.1, thank you for pointing that out.
