### ISSUE TITLE
How to stop working on localhost adress?

### ISSUE THREAD

**Issue by haXhaX312** [iinc0gnit0/BlackPhish#24]
I uninstalled blackfish, but blackfish continues to work when I go to 127.0.0.1:80.
How can I fix it?

**Comment by haXhaX312** [comment]
I uninstalled the package apache2 necessary for the program to work and this helped, but the main problem remained as if you reinstall apache2 program will run and work at 127.0.0.1:80.

If you have a solution to this problem please post it here

**Comment by Greatest125** [comment]
The following commands resolved the issue for me. 

`sudo apt purge apache2`
`sudo rm -r /var/www/html`
and finally 
`sudo apt install apache2`

After using these commands, (when I go to localhost) I get the default Apache page.

Hope this works!

**Comment by haXhaX312** [comment]
That helped! Thank you.
