### ISSUE TITLE
Grab a CI check???

### ISSUE THREAD

**Issue by Bobbbay** [iinc0gnit0/BlackPhish#5]
A [CircleCI](https://circleci.com/) check would really help the project gain trust (it works!), so there should probably be one running nightly or something. This should be done by @iinc0gnit0, because it **is** his repo, after all ;). 

Not sure if this is needed, but would help.

P.S. Sorry for the spam, I **finally** found a repo that I like + matches my skills so I'm *commiting* to it (see what I did there 🤣)

Happy 🐟-ing (another one), Bobbbay

**Comment by iinc0gnit0** [comment]
Don't worry about it, we are always welcome to new ideas and improvements. Don't be afraid to commit to this project. :wink:
