### ISSUE TITLE
Internet not found... 

### ISSUE THREAD

**Issue by Bobbbay** [iinc0gnit0/BlackPhish#6]
Pretty much, I just `sudo python3 blackphish.py`, and I get an `Internet Not Found` error. Here's the thing, though: I can `ping` and `wget` easy-peasy! 

I dunno, I just updated it, I've run it clean before, but this was a problem before I updated it too, I believe. 

Not that this is important, but:
- RPi 2b
- arm (duh)
- 64gb of space, used 12%
- Using a WiFi/USB dongle thing, CanaKit

Thanks, Bobbbay

**Comment by Bobbbay** [comment]
I think it's because apache's still running, because my WiFi dongle is telling me that somebody's using internet... I've tried killing all processes on my user as well as root, to no avail. At one point (after killing all the 20th time), the WiFi dongle stopped showing it's light, but it still wasn't working...

**Comment by iinc0gnit0** [comment]
Sorry to hear about that, have you tried to run [0] Clean yet?

**Comment by iinc0gnit0** [comment]
I have now fixed it, the problem was just a simple typo. Thanks for helping to improve BlackPhish.
